main: thirtyvirus.skyblock.nes
version: 1.3
name: NotEnoughSkyBlock
api-version: 1.13

commands:
  wandoops:
    description: Restore blocks accidentally placed by the builder's wand

softdepend: [UberItems]