main: thirtyvirus.skyblock.UberItems_SkyBlock
version: 1.2
name: UberItemsSkyBlock
api-version: 1.13

commands:
  wandoops:
    description: Restore blocks accidentally placed by the builder's wand

softdepend: [UberItems]